# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Ahmed\OneDrive - Virginia Tech\03.Work\02.VTTI\02.ResearchWork\01.Trains\02.Code\00.CPP\NeTrainSim\NeTrainSim\NeTrainSim\netrainsim.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NeTrainSim(object):
    def setupUi(self, NeTrainSim):
        NeTrainSim.setObjectName("NeTrainSim")
        NeTrainSim.resize(1318, 804)
        self.centralwidget = QtWidgets.QWidget(NeTrainSim)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_next = QtWidgets.QHBoxLayout()
        self.horizontalLayout_next.setObjectName("horizontalLayout_next")
        self.label_Notification = DisappearingLabel(self.centralwidget)
        self.label_Notification.setText("")
        self.label_Notification.setObjectName("label_Notification")
        self.horizontalLayout_next.addWidget(self.label_Notification)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_next.addItem(spacerItem)
        self.progressBar = CustomProgressBar(self.centralwidget)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 0))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setFormat("%p%")
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_next.addWidget(self.progressBar)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_next.addItem(spacerItem1)
        self.pushButton_projectNext = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_projectNext.setObjectName("pushButton_projectNext")
        self.horizontalLayout_next.addWidget(self.pushButton_projectNext)
        self.gridLayout_2.addLayout(self.horizontalLayout_next, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget_project = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_project.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_project.setTabsClosable(False)
        self.tabWidget_project.setObjectName("tabWidget_project")
        self.generalTab = QtWidgets.QWidget()
        self.generalTab.setObjectName("generalTab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.generalTab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.generalGridLayout = QtWidgets.QGridLayout()
        self.generalGridLayout.setObjectName("generalGridLayout")
        self.horizontalLayout_createdBy = QtWidgets.QHBoxLayout()
        self.horizontalLayout_createdBy.setObjectName("horizontalLayout_createdBy")
        self.label_createdBy = QtWidgets.QLabel(self.generalTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_createdBy.sizePolicy().hasHeightForWidth())
        self.label_createdBy.setSizePolicy(sizePolicy)
        self.label_createdBy.setMinimumSize(QtCore.QSize(100, 0))
        self.label_createdBy.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_createdBy.setObjectName("label_createdBy")
        self.horizontalLayout_createdBy.addWidget(self.label_createdBy)
        self.lineEdit_createdBy = QtWidgets.QLineEdit(self.generalTab)
        self.lineEdit_createdBy.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_createdBy.setObjectName("lineEdit_createdBy")
        self.horizontalLayout_createdBy.addWidget(self.lineEdit_createdBy)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_createdBy.addItem(spacerItem2)
        self.generalGridLayout.addLayout(self.horizontalLayout_createdBy, 1, 0, 1, 1)
        self.horizontalLayout_projectName = QtWidgets.QHBoxLayout()
        self.horizontalLayout_projectName.setObjectName("horizontalLayout_projectName")
        self.label_projectName = QtWidgets.QLabel(self.generalTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_projectName.sizePolicy().hasHeightForWidth())
        self.label_projectName.setSizePolicy(sizePolicy)
        self.label_projectName.setMinimumSize(QtCore.QSize(100, 0))
        self.label_projectName.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_projectName.setObjectName("label_projectName")
        self.horizontalLayout_projectName.addWidget(self.label_projectName)
        self.lineEdit_projectName = QtWidgets.QLineEdit(self.generalTab)
        self.lineEdit_projectName.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_projectName.setObjectName("lineEdit_projectName")
        self.horizontalLayout_projectName.addWidget(self.lineEdit_projectName)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_projectName.addItem(spacerItem3)
        self.generalGridLayout.addLayout(self.horizontalLayout_projectName, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.generalGridLayout.addItem(spacerItem4, 2, 0, 1, 1)
        self.gridLayout_9.addLayout(self.generalGridLayout, 0, 0, 1, 1)
        self.tabWidget_project.addTab(self.generalTab, "")
        self.NetworkTab = QtWidgets.QWidget()
        self.NetworkTab.setObjectName("NetworkTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.NetworkTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_oldNetwork = QtWidgets.QWidget(self.NetworkTab)
        self.widget_oldNetwork.setEnabled(True)
        self.widget_oldNetwork.setMaximumSize(QtCore.QSize(16777215, 93))
        self.widget_oldNetwork.setObjectName("widget_oldNetwork")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_oldNetwork)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.layout_oldNetwork = QtWidgets.QGridLayout()
        self.layout_oldNetwork.setObjectName("layout_oldNetwork")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget_oldNetwork)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_oldNetwork)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_4.addWidget(self.lineEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_oldNetwork)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.layout_oldNetwork.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.widget_oldNetwork)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_oldNetwork)
        self.lineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget_oldNetwork)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 0, 3, 1, 1)
        self.layout_oldNetwork.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.layout_oldNetwork, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_oldNetwork, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem7, 3, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_defineNewNetwork = QtWidgets.QCheckBox(self.NetworkTab)
        self.checkBox_defineNewNetwork.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.checkBox_defineNewNetwork.setObjectName("checkBox_defineNewNetwork")
        self.horizontalLayout.addWidget(self.checkBox_defineNewNetwork)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.widget_newNetwork = QtWidgets.QWidget(self.NetworkTab)
        self.widget_newNetwork.setObjectName("widget_newNetwork")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_newNetwork)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.layout_defineNewNetwork = QtWidgets.QHBoxLayout()
        self.layout_defineNewNetwork.setObjectName("layout_defineNewNetwork")
        self.tabWidget_defineNetwork = QtWidgets.QTabWidget(self.widget_newNetwork)
        self.tabWidget_defineNetwork.setObjectName("tabWidget_defineNetwork")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setMinimumSize(QtCore.QSize(140, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.doubleSpinBox_xCoordinate = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_xCoordinate.setMaximum(1e+17)
        self.doubleSpinBox_xCoordinate.setProperty("value", 1.0)
        self.doubleSpinBox_xCoordinate.setObjectName("doubleSpinBox_xCoordinate")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_xCoordinate)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setMinimumSize(QtCore.QSize(140, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.doubleSpinBox_yCoordinate = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_yCoordinate.setMaximum(1e+17)
        self.doubleSpinBox_yCoordinate.setProperty("value", 1.0)
        self.doubleSpinBox_yCoordinate.setObjectName("doubleSpinBox_yCoordinate")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_yCoordinate)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.gridLayout_8.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.table_newNodes = CustomTableWidget(self.tab_3)
        self.table_newNodes.setObjectName("table_newNodes")
        self.table_newNodes.setColumnCount(4)
        self.table_newNodes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.table_newNodes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_newNodes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_newNodes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.table_newNodes.setHorizontalHeaderItem(3, item)
        self.table_newNodes.horizontalHeader().setDefaultSectionSize(180)
        self.gridLayout_8.addWidget(self.table_newNodes, 1, 0, 1, 1)
        self.tabWidget_defineNetwork.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setMinimumSize(QtCore.QSize(140, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_2.setMaximum(1e+17)
        self.doubleSpinBox_2.setProperty("value", 1.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_2)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setMinimumSize(QtCore.QSize(140, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_3.setMaximum(1e+17)
        self.doubleSpinBox_3.setProperty("value", 1.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_3)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.gridLayout_10.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.table_newLinks = CustomTableWidget(self.tab_4)
        self.table_newLinks.setObjectName("table_newLinks")
        self.table_newLinks.setColumnCount(9)
        self.table_newLinks.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.table_newLinks.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_newLinks.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_newLinks.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_newLinks.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_newLinks.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_newLinks.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_newLinks.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_newLinks.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.table_newLinks.setHorizontalHeaderItem(8, item)
        self.table_newLinks.horizontalHeader().setDefaultSectionSize(180)
        self.gridLayout_10.addWidget(self.table_newLinks, 1, 0, 1, 1)
        self.tabWidget_defineNetwork.addTab(self.tab_4, "")
        self.layout_defineNewNetwork.addWidget(self.tabWidget_defineNetwork)
        self.plot_createNetwork = QCustomPlot(self.widget_newNetwork)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_createNetwork.sizePolicy().hasHeightForWidth())
        self.plot_createNetwork.setSizePolicy(sizePolicy)
        self.plot_createNetwork.setMinimumSize(QtCore.QSize(467, 0))
        self.plot_createNetwork.setObjectName("plot_createNetwork")
        self.layout_defineNewNetwork.addWidget(self.plot_createNetwork)
        self.gridLayout_7.addLayout(self.layout_defineNewNetwork, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_newNetwork, 2, 0, 1, 1)
        self.tabWidget_project.addTab(self.NetworkTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.widget_oldNetwork_2 = QtWidgets.QWidget(self.tab)
        self.widget_oldNetwork_2.setEnabled(True)
        self.widget_oldNetwork_2.setMaximumSize(QtCore.QSize(16777215, 93))
        self.widget_oldNetwork_2.setObjectName("widget_oldNetwork_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_oldNetwork_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.layout_oldNetwork_2 = QtWidgets.QGridLayout()
        self.layout_oldNetwork_2.setObjectName("layout_oldNetwork_2")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_8 = QtWidgets.QLabel(self.widget_oldNetwork_2)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setObjectName("label_8")
        self.gridLayout_12.addWidget(self.label_8, 0, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_oldNetwork_2)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_12.addWidget(self.lineEdit_4, 0, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_oldNetwork_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_12.addWidget(self.pushButton_4, 0, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem12, 0, 3, 1, 1)
        self.layout_oldNetwork_2.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.layout_oldNetwork_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_oldNetwork_2)
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setObjectName("widget")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget_2 = CustomTableWidget(self.tab_6)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(8)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(140)
        self.verticalLayout_2.addWidget(self.tableWidget_2)
        self.tableWidget = CustomTableWidget(self.tab_6)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(140)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.gridLayout_15.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_4 = CustomTableWidget(self.tab_7)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(4)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(140)
        self.verticalLayout_3.addWidget(self.tableWidget_4)
        self.tableWidget_3 = CustomTableWidget(self.tab_7)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(7)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(140)
        self.verticalLayout_3.addWidget(self.tableWidget_3)
        self.gridLayout_16.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_2 = QCustomPlot(self.tab_8)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.verticalLayout_4.addWidget(self.widget_2)
        self.gridLayout_17.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.comboBox = QtWidgets.QComboBox(self.tab_8)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_5.addWidget(self.comboBox)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.gridLayout_17.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_8, "")
        self.gridLayout_14.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.gridLayout_13.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget_project.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_19.setObjectName("gridLayout_19")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem14, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalGroupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.verticalGroupBox_6.setObjectName("verticalGroupBox_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalGroupBox_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.verticalGroupBox_6)
        self.label_7.setMinimumSize(QtCore.QSize(150, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.verticalGroupBox_6)
        self.doubleSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.doubleSpinBox.setMaximum(999999999999.98)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_11.addWidget(self.doubleSpinBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.verticalGroupBox_6)
        self.label_9.setMinimumSize(QtCore.QSize(150, 0))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.verticalGroupBox_6)
        self.doubleSpinBox_4.setSingleStep(0.1)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.horizontalLayout_12.addWidget(self.doubleSpinBox_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.verticalGroupBox_6)
        self.label_10.setMinimumSize(QtCore.QSize(150, 0))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.verticalGroupBox_6)
        self.doubleSpinBox_5.setSingleStep(50.0)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.horizontalLayout_10.addWidget(self.doubleSpinBox_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8.addWidget(self.verticalGroupBox_6)
        self.verticalGroupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        self.verticalGroupBox_7.setObjectName("verticalGroupBox_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalGroupBox_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalGroupBox_7)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_14.addWidget(self.checkBox_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        spacerItem15 = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_7.addItem(spacerItem15)
        self.horizontalLayout_8.addWidget(self.verticalGroupBox_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.gridLayout_20.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalGroupBox_61 = QtWidgets.QGroupBox(self.groupBox)
        self.verticalGroupBox_61.setObjectName("verticalGroupBox_61")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalGroupBox_61)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_11 = QtWidgets.QLabel(self.verticalGroupBox_61)
        self.label_11.setMinimumSize(QtCore.QSize(152, 0))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_15.addWidget(self.label_11)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalGroupBox_61)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_15.addWidget(self.lineEdit_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalGroupBox_61)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_15.addWidget(self.pushButton_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_12 = QtWidgets.QLabel(self.verticalGroupBox_61)
        self.label_12.setMinimumSize(QtCore.QSize(152, 0))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_16.addWidget(self.label_12)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalGroupBox_61)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_16.addWidget(self.lineEdit_5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.checkBox_3 = QtWidgets.QCheckBox(self.verticalGroupBox_61)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_17.addWidget(self.checkBox_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalWidget_6 = QtWidgets.QWidget(self.verticalGroupBox_61)
        self.horizontalWidget_6.setObjectName("horizontalWidget_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalWidget_6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.horizontalWidget_6)
        self.label_13.setMinimumSize(QtCore.QSize(153, 0))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.horizontalWidget_6)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_13.addWidget(self.lineEdit_6)
        self.verticalLayout_8.addWidget(self.horizontalWidget_6)
        self.gridLayout_20.addWidget(self.verticalGroupBox_61, 1, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem16, 1, 0, 1, 1)
        self.tabWidget_project.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_5)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem17)
        self.pushButton_popoutPreview = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_popoutPreview.setObjectName("pushButton_popoutPreview")
        self.horizontalLayout_2.addWidget(self.pushButton_popoutPreview)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_SummaryReport = QPrintPreviewWidget(self.tab_9)
        self.widget_SummaryReport.setObjectName("widget_SummaryReport")
        self.verticalLayout_12.addWidget(self.widget_SummaryReport)
        self.verticalLayout_11.addLayout(self.verticalLayout_12)
        self.gridLayout_22.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tabWidget_2.addTab(self.tab_10, "")
        self.gridLayout_21.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget_project.addTab(self.tab_5, "")
        self.gridLayout.addWidget(self.tabWidget_project, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        NeTrainSim.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NeTrainSim)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1318, 25))
        self.menubar.setObjectName("menubar")
        self.menuNeTrainSim = QtWidgets.QMenu(self.menubar)
        self.menuNeTrainSim.setObjectName("menuNeTrainSim")
        NeTrainSim.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NeTrainSim)
        self.statusbar.setObjectName("statusbar")
        NeTrainSim.setStatusBar(self.statusbar)
        self.actionNew_Project = QtWidgets.QAction(NeTrainSim)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.actionOpen_a_project = QtWidgets.QAction(NeTrainSim)
        self.actionOpen_a_project.setObjectName("actionOpen_a_project")
        self.menuNeTrainSim.addAction(self.actionNew_Project)
        self.menuNeTrainSim.addAction(self.actionOpen_a_project)
        self.menubar.addAction(self.menuNeTrainSim.menuAction())

        self.retranslateUi(NeTrainSim)
        self.tabWidget_project.setCurrentIndex(1)
        self.tabWidget_defineNetwork.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NeTrainSim)

    def retranslateUi(self, NeTrainSim):
        _translate = QtCore.QCoreApplication.translate
        NeTrainSim.setWindowTitle(_translate("NeTrainSim", "NeTrainSim"))
        self.pushButton_projectNext.setText(_translate("NeTrainSim", "Next"))
        self.label_createdBy.setText(_translate("NeTrainSim", "Created by:"))
        self.label_projectName.setText(_translate("NeTrainSim", "Project name:"))
        self.tabWidget_project.setTabText(self.tabWidget_project.indexOf(self.generalTab), _translate("NeTrainSim", "General Info"))
        self.label_2.setText(_translate("NeTrainSim", "Links file"))
        self.pushButton_2.setText(_translate("NeTrainSim", "Browse"))
        self.label.setText(_translate("NeTrainSim", "Nodes file"))
        self.pushButton.setText(_translate("NeTrainSim", "Browse"))
        self.checkBox_defineNewNetwork.setText(_translate("NeTrainSim", "Create new network"))
        self.label_5.setText(_translate("NeTrainSim", "X-Coordinates Scale:"))
        self.label_6.setText(_translate("NeTrainSim", "Y-Coordinates Scale:"))
        item = self.table_newNodes.horizontalHeaderItem(0)
        item.setText(_translate("NeTrainSim", "Identification Number (ID)"))
        item = self.table_newNodes.horizontalHeaderItem(1)
        item.setText(_translate("NeTrainSim", "X Coordinate (m)"))
        item = self.table_newNodes.horizontalHeaderItem(2)
        item.setText(_translate("NeTrainSim", "Y Coordinate (m)"))
        item = self.table_newNodes.horizontalHeaderItem(3)
        item.setText(_translate("NeTrainSim", "Description"))
        self.tabWidget_defineNetwork.setTabText(self.tabWidget_defineNetwork.indexOf(self.tab_3), _translate("NeTrainSim", "Nodes"))
        self.label_3.setText(_translate("NeTrainSim", "Length Scale:"))
        self.label_4.setText(_translate("NeTrainSim", "Speed Scale:"))
        item = self.table_newLinks.horizontalHeaderItem(0)
        item.setText(_translate("NeTrainSim", "Identification Number (ID)"))
        item = self.table_newLinks.horizontalHeaderItem(1)
        item.setText(_translate("NeTrainSim", "From (Node ID)"))
        item = self.table_newLinks.horizontalHeaderItem(2)
        item.setText(_translate("NeTrainSim", "To (Node ID)"))
        item = self.table_newLinks.horizontalHeaderItem(3)
        item.setText(_translate("NeTrainSim", "Free Flow Speed (m/s)"))
        item = self.table_newLinks.horizontalHeaderItem(4)
        item.setText(_translate("NeTrainSim", "Curvature (Ratio)"))
        item = self.table_newLinks.horizontalHeaderItem(5)
        item.setText(_translate("NeTrainSim", "Grade (Ratio)"))
        item = self.table_newLinks.horizontalHeaderItem(6)
        item.setText(_translate("NeTrainSim", "is two directional?"))
        item = self.table_newLinks.horizontalHeaderItem(7)
        item.setText(_translate("NeTrainSim", "Has gantry?"))
        item = self.table_newLinks.horizontalHeaderItem(8)
        item.setText(_translate("NeTrainSim", "Description"))
        self.tabWidget_defineNetwork.setTabText(self.tabWidget_defineNetwork.indexOf(self.tab_4), _translate("NeTrainSim", "Links"))
        self.tabWidget_project.setTabText(self.tabWidget_project.indexOf(self.NetworkTab), _translate("NeTrainSim", "Network Definition"))
        self.checkBox.setText(_translate("NeTrainSim", "Create new Train OD Pairs"))
        self.label_8.setText(_translate("NeTrainSim", "Trains File"))
        self.pushButton_4.setText(_translate("NeTrainSim", "Browse"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("NeTrainSim", "ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("NeTrainSim", "Power (kW)"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("NeTrainSim", "Number of Axiles"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("NeTrainSim", "Streamlining Coef."))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("NeTrainSim", "Frontal Area (sq m)"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("NeTrainSim", "Length (m)"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("NeTrainSim", "Weight (t)"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("NeTrainSim", "Energy Type"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("NeTrainSim", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("NeTrainSim", "Number of Axiles"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("NeTrainSim", "Frontal Area (sq m)"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("NeTrainSim", "Length (m)"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("NeTrainSim", "Current Weight (t)"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("NeTrainSim", "Empty Weight (t)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("NeTrainSim", "Define Vehicles"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("NeTrainSim", "ID"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("NeTrainSim", "Type"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("NeTrainSim", "New Column"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("NeTrainSim", "Type ID"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("NeTrainSim", "New Column"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("NeTrainSim", "Configuration ID"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("NeTrainSim", "Nodes Along Path"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("NeTrainSim", "Start Time (Seconds)"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("NeTrainSim", "Number of Locos"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("NeTrainSim", "Number of Cars"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("NeTrainSim", "Friction Coefficient"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("NeTrainSim", "Define Train Consists"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("NeTrainSim", "Define Trains Paths"))
        self.tabWidget_project.setTabText(self.tabWidget_project.indexOf(self.tab), _translate("NeTrainSim", "Trains Definition"))
        self.groupBox.setTitle(_translate("NeTrainSim", "Simulation options"))
        self.verticalGroupBox_6.setTitle(_translate("NeTrainSim", "General"))
        self.label_7.setText(_translate("NeTrainSim", "Simulation time:"))
        self.label_9.setText(_translate("NeTrainSim", "Simulation time step:"))
        self.label_10.setText(_translate("NeTrainSim", "Draw output every:"))
        self.verticalGroupBox_7.setTitle(_translate("NeTrainSim", "Energy consumption optimization"))
        self.checkBox_2.setText(_translate("NeTrainSim", "Enable Optimization"))
        self.verticalGroupBox_61.setTitle(_translate("NeTrainSim", "Export options"))
        self.label_11.setText(_translate("NeTrainSim", "Output directory:"))
        self.pushButton_3.setText(_translate("NeTrainSim", "Browse"))
        self.label_12.setText(_translate("NeTrainSim", "Summary file name:"))
        self.checkBox_3.setText(_translate("NeTrainSim", "Export trajectory?"))
        self.label_13.setText(_translate("NeTrainSim", "Trajectory file name:"))
        self.tabWidget_project.setTabText(self.tabWidget_project.indexOf(self.tab_2), _translate("NeTrainSim", "Simulation"))
        self.pushButton_popoutPreview.setText(_translate("NeTrainSim", "Pop out"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("NeTrainSim", "Summary"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("NeTrainSim", "Detailed"))
        self.tabWidget_project.setTabText(self.tabWidget_project.indexOf(self.tab_5), _translate("NeTrainSim", "Results"))
        self.menuNeTrainSim.setTitle(_translate("NeTrainSim", "NeTrainSim"))
        self.actionNew_Project.setText(_translate("NeTrainSim", "Create a new project"))
        self.actionOpen_a_project.setText(_translate("NeTrainSim", "Open an existing project"))

from qprintpreviewwidget import QPrintPreviewWidget
from src.dependencies.qcustomplot.qcustomplot import QCustomPlot
from src.gui.CustomProgressBar import CustomProgressBar
from src.gui.CustomTableWidget import CustomTableWidget
from src.gui.DisappearingLabel import DisappearingLabel
